#!/usr/bin/env python3
"""Build batched benchmark kernels from fortfem's extracted primals.

Each fortfem operator is a handful of scalar arguments producing a handful of
scalar outputs. One evaluation is far below timer resolution, so each is wrapped
in a loop over a batch and its outputs summed - which is also how fortfem uses
them, once per cell or per quadrature point rather than once.

The wrapper is generated rather than written because the argument lists are:
forty-four operators with between three and twenty-four active arguments each.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

FORTFEM = Path("../fortfem")
OUT = Path("cases/fortfem/kernels")

# Operators worth timing: one from each shape rather than all forty-four, so the
# suite stays readable. The Bezier family is represented by its cheapest and its
# most expensive member, which is where a difference would show.
CHOSEN = [
    "fci_polygon_edge_area",
    "fci_quadrilateral_cell_area",
    "fci_quartic_bezier_edge_area",
    "fci_hendecic_bezier_edge_area",
    "fci_parallel_gradient",
    "fci_quintic_lagrange_weights",
    "cgl_pressure_tensor",
    "bspline_h1_geometry",
    "laplace_single_layer_integrand",
    "surface_triangle_geometry_3d",
]


def body_of(source: str, name: str) -> tuple[list[str], str]:
    """The executable statements of a primal, and its local declarations.

    Continuations are joined first. Without that, the tail of a continued
    declaration is a line that starts with neither a type keyword nor an
    `intent`, and it lands in the statement list as a bare name - which parses
    as nothing and fails several statements later with a confusing message.
    """
    text = re.sub(r"&\s*\n\s*", "", source)
    start = text.index("implicit none")
    end = text.rindex("end subroutine")
    lines = text[start + len("implicit none"):end].split("\n")
    decls, stmts = [], []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("!"):
            continue
        if re.match(r"^(real|integer|logical)\b", stripped):
            if "intent(" not in stripped:
                decls.append(stripped)
            continue
        stmts.append(stripped)
    return stmts, "\n".join(f"    {d}" for d in decls)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    catalogue = {e["stem"]: e
                 for e in json.loads((FORTFEM / "tools/fortad/catalogue.json")
                                     .read_text())}
    made = []
    for stem in CHOSEN:
        entry = catalogue.get(stem)
        if entry is None:
            print(f"  no such operator: {stem}")
            continue
        source = (FORTFEM / "tools/fortad/kernels" / f"{stem}.f90").read_text()
        args = re.search(r"subroutine \w+\(([^)]*)\)",
                         re.sub(r"&\s*\n\s*", "", source)).group(1)
        args = [a.strip() for a in args.split(",")]
        dims = entry.get("dims", {})
        if any(dims.get(a) for a in args):
            print(f"  skipped {stem}: array-shaped argument")
            continue
        inputs = [a for a in args if a not in entry["outputs"]]
        stmts, locals_text = body_of(source, stem)
        write_kernel(stem, inputs, entry["outputs"], stmts, locals_text)
        made.append((stem, len(inputs)))
    Path("cases/fortfem/arity.json").write_text(
        json.dumps({s: n for s, n in made}, indent=2) + "\n")
    print(f"wrote {len(made)} batched kernels")
    return 0


def write_kernel(stem, inputs, outputs, stmts, locals_text) -> None:
    n = len(inputs)
    unpack = "\n".join(f"        {name} = z(base + {i + 1})"
                       for i, name in enumerate(inputs))
    accumulate = "\n".join(f"        y = y + {name}" for name in outputs)
    decl_in = wrap_names("    real(dp) :: ", inputs)
    decl_out = wrap_names("    real(dp) :: ", outputs)
    plain = f"""subroutine {stem}(n, z, y)
    !! {stem} over a batch, its outputs summed.
    !!
    !! Generated by scripts/make_fortfem_cases.py from fortfem's extracted
    !! primal. One evaluation is far below timer resolution, and a batch is how
    !! fortfem uses these - once per cell or per quadrature point.
    use, intrinsic :: iso_fortran_env, only: dp => real64
    implicit none
    integer, intent(in) :: n
    real(dp), intent(in) :: z({n}*n)
    real(dp), intent(out) :: y
    integer :: i, base
{decl_in}
{decl_out}
{locals_text}

    y = 0.0_dp
    do i = 1, n
        base = {n}*(i - 1)
{unpack}
""" + "\n".join(f"        {s}" for s in stmts) + f"""
{accumulate}
    end do
end subroutine {stem}
"""
    (OUT / f"{stem}.f90").write_text(plain)

    c = plain.replace(f"subroutine {stem}(n, z, y)",
                      f'subroutine {stem}(n, z, y) bind(C, name="{stem}")', 1)
    c = c.replace("    use, intrinsic :: iso_fortran_env, only: dp => real64",
                  "    use, intrinsic :: iso_c_binding, only: c_int, dp => c_double")
    c = c.replace("    integer, intent(in) :: n",
                  "    integer(c_int), intent(in), value :: n")
    (OUT / f"{stem}_c.f90").write_text(c)


def wrap_names(prefix: str, names: list[str]) -> str:
    line, out = prefix, []
    for i, name in enumerate(names):
        piece = name + (", " if i < len(names) - 1 else "")
        if len(line) + len(piece) > 80:
            out.append(line + "&")
            line = "        "
        line += piece
    out.append(line)
    return "\n".join(out)


if __name__ == "__main__":
    sys.exit(main())
