#!/usr/bin/env python3
"""Batch wrappers around fortnum's fortsym-generated derivative kernels.

fortsym emits one scalar kernel per operator per product. The benchmark applies
each operator over a batch, so each kernel needs a loop around it - the same
loop the fortad and Enzyme entry points have, so what is timed is the kernel
rather than three different callers.

erf and erfc are left out: their fortsym kernels take assumed-shape arrays and
assign only element one, so a batch of them would measure a scalar.
"""

from __future__ import annotations

import sys
from pathlib import Path

OUT = Path("cases/fortnum/fortsym")

# operator : arguments : whether the products also return the primal value
SPECS = [
    ("det2", ["a", "b", "c", "d"], False),
    ("det3", ["a", "b", "c", "d", "f", "g", "h", "j", "k"], False),
    ("lagrange4", ["x", "y1", "y2", "y3", "y4"], True),
    ("multi_input_p2", [f"x{i}" for i in range(1, 3)], True),
    ("multi_input_p4", [f"x{i}" for i in range(1, 5)], True),
    ("multi_input_p8", [f"x{i}" for i in range(1, 9)], True),
    ("multi_input_p16", [f"x{i}" for i in range(1, 17)], True),
]

# fortsym names its tangent and adjoint arguments differently per generator.
TANGENT = {
    "det2": ["va", "vb", "vc", "vd"],
    "det3": ["ta", "tb", "tc", "td", "tf", "tg", "th", "tj", "tk"],
    "lagrange4": ["tx", "ty1", "ty2", "ty3", "ty4"],
}
ADJOINT = {
    "det2": ["ba", "bb", "bc", "bd"],
    "det3": ["ba", "bb", "bc", "bd", "bf", "bg", "bh", "bj", "bk"],
    "lagrange4": ["adjoint_x", "adjoint_y1", "adjoint_y2", "adjoint_y3",
                  "adjoint_y4"],
}


def wrap(prefix: str, items: list[str], suffix: str = ")") -> str:
    line, out = prefix, []
    for i, item in enumerate(items):
        piece = item + (", " if i < len(items) - 1 else suffix)
        if len(line) + len(piece) > 82:
            out.append(line + "&")
            line = " " * 12
        line += piece
    out.append(line)
    return "\n".join(out)


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    for op, args, with_value in SPECS:
        n = len(args)
        tangent = TANGENT.get(op, [f"v{i}" for i in range(1, n + 1)])
        adjoint = ADJOINT.get(op, [f"adjoint{i}" for i in range(1, n + 1)])
        loads = "\n".join(f"            {a} = z(base + {i + 1})"
                          for i, a in enumerate(args))
        dloads = "\n".join(f"            {t} = dz(base + {i + 1})"
                           for i, t in enumerate(tangent))
        scatter = "\n".join(f"            z_b(base + {i + 1}) = {a}"
                            for i, a in enumerate(adjoint))
        jvp_args = args + tangent + (["value", "tangent"] if with_value
                                     else ["tangent"])
        vjp_args = args + ["u"] + (["value"] if with_value else []) + adjoint
        decls = wrap("        real(dp) :: ",
                     args + tangent + adjoint + ["value"], suffix="")
        Path(OUT / f"{op}_fortsym.f90").write_text(f"""\
module fortnum_fortsym_{op}
    !! A batch loop around fortsym's {op} kernels.
    !!
    !! Generated by scripts/make_fortsym_wrappers.py. The loop is the same one
    !! the fortad and Enzyme entry points have, so what is timed is the kernel
    !! rather than three different callers.
    use, intrinsic :: iso_fortran_env, only: dp => real64
    use fortnum_generated_{op}_jvp, only: fortnum_{op}_jvp_kernel
    use fortnum_generated_{op}_vjp, only: fortnum_{op}_vjp_kernel
    implicit none
    private

    public :: {op}_jvp_fortsym, {op}_vjp_fortsym

contains

    subroutine {op}_jvp_fortsym(n, z, dz, y, dy)
        integer, intent(in) :: n
        real(dp), intent(in) :: z({n}*n), dz({n}*n)
        real(dp), intent(out) :: y, dy
        integer :: i, base
        real(dp) :: tangent
{decls}

        y = 0.0_dp
        dy = 0.0_dp
        do i = 1, n
            base = {n}*(i - 1)
{loads}
{dloads}
{wrap("            call fortnum_" + op + "_jvp_kernel(", jvp_args)}
            dy = dy + tangent
{"            y = y + value" if with_value else ""}
        end do
    end subroutine {op}_jvp_fortsym

    subroutine {op}_vjp_fortsym(n, z, y_b, z_b)
        integer, intent(in) :: n
        real(dp), intent(in) :: z({n}*n)
        real(dp), intent(in) :: y_b
        real(dp), intent(out) :: z_b({n}*n)
        integer :: i, base
        real(dp) :: u
{decls}

        u = y_b
        do i = 1, n
            base = {n}*(i - 1)
{loads}
{wrap("            call fortnum_" + op + "_vjp_kernel(", vjp_args)}
{scatter}
        end do
    end subroutine {op}_vjp_fortsym

end module fortnum_fortsym_{op}
""")
    print(f"wrote {len(SPECS)} fortsym batch wrappers")
    return 0


if __name__ == "__main__":
    sys.exit(main())
