#!/usr/bin/env bash
set -euo pipefail

case_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
root=$(cd "$case_dir/../../.." && pwd)
result="$case_dir/result.txt"
fortad_repo=$(cd "${FORTAD_REPO:-$root/../fortad}" && pwd)
tapenade_repo=$(cd "${TAPENADE_REPO:-$root/upstream/tapenade}" && pwd)
required_fortad_commit=93f41d60d882778699ec1a887ce9a665a75afcf8
required_tapenade_commit=e59864cab441d4175df75383b3ff58c3dcd26df9
fc=${FC:-gfortran}
source_rel=nonRegressions/set01/lh104
source_dir="$tapenade_repo/$source_rel"
fortad="$fortad_repo/build/fo/bin/fortad"
tapenade="$tapenade_repo/bin/tapenade"
out=$(mktemp -d /var/tmp/fortad-bench-lh104.XXXXXX)
trap 'rm -rf "$out"' EXIT

command -v "$fc" >/dev/null
command -v python3 >/dev/null
command -v java >/dev/null
test "$(git -C "$fortad_repo" rev-parse HEAD)" = "$required_fortad_commit"
test "$(git -C "$tapenade_repo" rev-parse HEAD)" = "$required_tapenade_commit"
test -z "$(git -C "$tapenade_repo" status --porcelain --untracked-files=no)"
test -x "$fortad" && test -x "$tapenade"
for source in program.f program_b.f; do test -s "$source_dir/$source"; done

strict_fixed=(-std=f2018 -ffixed-form -ffixed-line-length-none -pedantic-errors -Wall -Wextra -Wimplicit-interface -fsyntax-only)
legacy_fixed=(-std=legacy -ffixed-form -ffixed-line-length-none -Wall -Wextra -Wimplicit-interface -fsyntax-only)
strict_free=(-std=f2018 -ffree-form -ffree-line-length-none -pedantic-errors -Wall -Wextra -Wimplicit-interface -fsyntax-only)
legacy_free=(-std=legacy -ffree-form -ffree-line-length-none -Wall -Wextra -Wimplicit-interface -fsyntax-only)

run_status() {
    local label=$1
    shift
    local rc=0
    "$@" >"$out/$label.stdout" 2>"$out/$label.stderr" || rc=$?
    printf '%s\n' "$rc" >"$out/$label.status"
}

status() { cat "$out/$1.status"; }

mkdir -p "$out/fresh/parser" "$out/fresh/forward" "$out/fresh/reverse" "$out/fortad"

run_status exact-strict "$fc" "${strict_fixed[@]}" "$source_dir/program.f"
run_status exact-legacy "$fc" "${legacy_fixed[@]}" "$source_dir/program.f"
run_status stored-strict "$fc" "${strict_fixed[@]}" "$source_dir/program_b.f"
run_status stored-legacy "$fc" "${legacy_fixed[@]}" "$source_dir/program_b.f"
test "$(status exact-strict)" -eq 0
test "$(status exact-legacy)" -eq 0
test "$(status stored-strict)" -ne 0
test "$(status stored-legacy)" -eq 0

for mode in parser forward reverse; do
    case "$mode" in
        parser) flag=-p; suffix=p ;;
        forward) flag=-d; suffix=d ;;
        reverse) flag=-b; suffix=b ;;
    esac
    run_status "tapenade-$mode" bash -c "cd '$out/fresh/$mode' && '$tapenade' '$flag' -root top -O . -o lh104 '$source_dir/program.f'"
    test "$(status "tapenade-$mode")" -eq 0
    test -f "$out/fresh/$mode/lh104_${suffix}.f"
    test -f "$out/fresh/$mode/lh104_${suffix}.msg"
    run_status "fresh-$mode-strict" "$fc" "${strict_fixed[@]}" "$out/fresh/$mode/lh104_${suffix}.f"
    run_status "fresh-$mode-legacy" "$fc" "${legacy_fixed[@]}" "$out/fresh/$mode/lh104_${suffix}.f"
    if test "$mode" = reverse; then
        test "$(status "fresh-$mode-strict")" -ne 0
        test "$(status "fresh-$mode-legacy")" -eq 0
    else
        test "$(status "fresh-$mode-strict")" -eq 0
        test "$(status "fresh-$mode-legacy")" -eq 0
    fi
done

diff -I '^C        Generated by TAPENADE' -I '^C  Tapenade ' "$source_dir/program_b.f" "$out/fresh/reverse/lh104_b.f" >/dev/null

run_status fortad-check "$fortad" check --proc top --output "$out/fortad/check.f" "$source_dir/program.f"
test "$(status fortad-check)" -eq 0
run_status fortad-check-strict "$fc" "${strict_free[@]}" "$out/fortad/check.f"
run_status fortad-check-legacy "$fc" "${legacy_free[@]}" "$out/fortad/check.f"
test "$(status fortad-check-strict)" -eq 0
test "$(status fortad-check-legacy)" -eq 0

run_status fortad-forward "$fortad" --mode forward --proc top --indep a,b,c,d --name top_d --module top_d_mod --output "$out/fortad/forward.f" "$source_dir/program.f"
test "$(status fortad-forward)" -eq 0
test -s "$out/fortad/forward.f"
run_status fortad-forward-strict "$fc" "${strict_free[@]}" "$out/fortad/forward.f"
run_status fortad-forward-legacy "$fc" "${legacy_free[@]}" "$out/fortad/forward.f"
test "$(status fortad-forward-strict)" -eq 0
test "$(status fortad-forward-legacy)" -eq 0

run_status fortad-reverse "$fortad" --mode reverse --proc top --indep a,b,c --dep d --name top_b --module top_b_mod --output "$out/fortad/reverse.f" "$source_dir/program.f"
test "$(status fortad-reverse)" -eq 0
test -s "$out/fortad/reverse.f"
run_status fortad-reverse-strict "$fc" "${strict_free[@]}" "$out/fortad/reverse.f"
run_status fortad-reverse-legacy "$fc" "${legacy_free[@]}" "$out/fortad/reverse.f"
test "$(status fortad-reverse-strict)" -ne 0
test "$(status fortad-reverse-legacy)" -ne 0
grep -Fq 'd_b' "$out/fortad-reverse-strict.stderr"
grep -Fq 'INTENT(IN)' "$out/fortad-reverse-strict.stderr"

python3 "$case_dir/oracle.py" "$source_dir" >"$out/oracle.txt"
grep -Fq 'oracle_status: pass' "$out/oracle.txt"

{
    printf 'case: Tapenade nonRegressions/set01/lh104\n'
    printf 'classification: expected-refusal-fortad-reverse-inout-adjoint-output\n'
    printf 'recorded_utc: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf 'fortad_commit: %s\n' "$(git -C "$fortad_repo" rev-parse HEAD)"
    printf 'tapenade_commit: %s\n' "$(git -C "$tapenade_repo" rev-parse HEAD)"
    printf 'compiler: %s\n' "$("$fc" --version | head -1)"
    printf 'upstream_entry_point: top(a,b,c,d)\n'
    printf 'strict_compile: exact=%s stored_reverse=%s fresh_parser=%s fresh_forward=%s fresh_reverse=%s fortad_check=%s fortad_forward=%s fortad_reverse=%s\n' \
        "$(status exact-strict)" "$(status stored-strict)" "$(status fresh-parser-strict)" "$(status fresh-forward-strict)" "$(status fresh-reverse-strict)" "$(status fortad-check-strict)" "$(status fortad-forward-strict)" "$(status fortad-reverse-strict)"
    printf 'legacy_compile: exact=%s stored_reverse=%s fresh_parser=%s fresh_forward=%s fresh_reverse=%s fortad_check=%s fortad_forward=%s fortad_reverse=%s\n' \
        "$(status exact-legacy)" "$(status stored-legacy)" "$(status fresh-parser-legacy)" "$(status fresh-forward-legacy)" "$(status fresh-reverse-legacy)" "$(status fortad-check-legacy)" "$(status fortad-forward-legacy)" "$(status fortad-reverse-legacy)"
    printf 'tapenade_generation: parser=%s forward=%s reverse=%s\n' "$(status tapenade-parser)" "$(status tapenade-forward)" "$(status tapenade-reverse)"
    printf 'tapenade_reverse_reference: fresh-body-equals-stored-after-banner-normalization\n'
    printf 'fortad_exact_behavior: check=pass forward_jvp=pass reverse_vjp=expected-refusal-output-fails-both-free-form-gates\n'
    cat "$out/oracle.txt"
    printf 'upstream_sha256:\n'
    (cd "$tapenade_repo" && sha256sum "$source_rel"/program.f "$source_rel"/program_b.f)
    printf 'fresh_tapenade_sha256:\n'
    (cd "$out/fresh" && sha256sum parser/lh104_p.f parser/lh104_p.msg forward/lh104_d.f forward/lh104_d.msg reverse/lh104_b.f reverse/lh104_b.msg)
    printf 'fortad_output_sha256:\n'
    sha256sum "$out/fortad/check.f" "$out/fortad/forward.f" "$out/fortad/reverse.f"
    printf 'case_artifact_sha256:\n'
    (cd "$case_dir" && sha256sum manifest.toml notes.md oracle.py run.sh test_contract.py)
} >"$result"
cat "$result"
