#!/usr/bin/env python3
"""Exactly three behavioral/generation contracts for the lh104 package."""

from __future__ import annotations

import os
import subprocess
import tempfile
import unittest
from pathlib import Path

CASE = Path(__file__).resolve().parent
BENCH = CASE.parents[2]
UPSTREAM = Path(os.environ.get("TAPENADE_REPO", str(BENCH / "upstream" / "tapenade")))
FORTAD_ROOT = Path(os.environ.get("FORTAD_REPO", str(BENCH.parent / "fortad")))
SOURCE_DIR = UPSTREAM / "nonRegressions" / "set01" / "lh104"
FORTAD = FORTAD_ROOT / "build" / "fo" / "bin" / "fortad"
TAPENADE = UPSTREAM / "bin" / "tapenade"
FC = os.environ.get("FC", "gfortran")
STRICT_FIXED = ("-std=f2018", "-ffixed-form", "-ffixed-line-length-none", "-pedantic-errors", "-Wall", "-Wextra", "-Wimplicit-interface", "-fsyntax-only")
LEGACY_FIXED = ("-std=legacy", "-ffixed-form", "-ffixed-line-length-none", "-Wall", "-Wextra", "-Wimplicit-interface", "-fsyntax-only")
STRICT_FREE = ("-std=f2018", "-ffree-form", "-ffree-line-length-none", "-pedantic-errors", "-Wall", "-Wextra", "-Wimplicit-interface", "-fsyntax-only")
LEGACY_FREE = ("-std=legacy", "-ffree-form", "-ffree-line-length-none", "-Wall", "-Wextra", "-Wimplicit-interface", "-fsyntax-only")


def run(command: list[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, capture_output=True, text=True, check=False)


class Lh104ContractTests(unittest.TestCase):
    def test_independent_branch_jvp_and_vjp_oracle(self) -> None:
        completed = run(["python3", str(CASE / "oracle.py"), str(SOURCE_DIR)])
        self.assertEqual(completed.returncode, 0, completed.stdout + completed.stderr)
        self.assertIn("oracle_branch_paths: pass", completed.stdout)
        self.assertIn("oracle_jvp_finite_difference: pass", completed.stdout)
        self.assertIn("oracle_vjp_dot_product: pass", completed.stdout)
        self.assertIn("oracle_status: pass", completed.stdout)

    def test_fresh_tapenade_generation_and_both_compiler_gates(self) -> None:
        with tempfile.TemporaryDirectory(prefix="fortad-lh104-tapenade-") as directory:
            output = Path(directory)
            for mode, flag, suffix in (("parser", "-p", "p"), ("forward", "-d", "d"), ("reverse", "-b", "b")):
                mode_dir = output / mode
                mode_dir.mkdir()
                generated = run([str(TAPENADE), flag, "-root", "top", "-O", ".", "-o", "lh104", str(SOURCE_DIR / "program.f")], cwd=mode_dir)
                self.assertEqual(generated.returncode, 0, f"{mode}: {generated.stdout}\n{generated.stderr}")
                source = mode_dir / f"lh104_{suffix}.f"
                message = mode_dir / f"lh104_{suffix}.msg"
                self.assertTrue(source.is_file(), source)
                self.assertTrue(message.is_file(), message)
                strict = run([FC, *STRICT_FIXED, str(source)])
                legacy = run([FC, *LEGACY_FIXED, str(source)])
                if mode == "reverse":
                    self.assertNotEqual(strict.returncode, 0, strict.stderr)
                    self.assertEqual(legacy.returncode, 0, legacy.stderr)
                else:
                    self.assertEqual(strict.returncode, 0, strict.stderr)
                    self.assertEqual(legacy.returncode, 0, legacy.stderr)
            fresh = [line for line in (output / "reverse" / "lh104_b.f").read_text().splitlines() if not line.startswith("C        Generated by TAPENADE") and not line.startswith("C  Tapenade ")]
            stored = [line for line in (SOURCE_DIR / "program_b.f").read_text().splitlines() if not line.startswith("C        Generated by TAPENADE") and not line.startswith("C  Tapenade ")]
            self.assertEqual(fresh, stored)

    def test_exact_fortad_check_forward_and_reverse_boundary(self) -> None:
        with tempfile.TemporaryDirectory(prefix="fortad-lh104-fortad-") as directory:
            output = Path(directory)
            source = SOURCE_DIR / "program.f"
            check = run([str(FORTAD), "check", "--proc", "top", "--output", str(output / "check.f"), str(source)])
            self.assertEqual(check.returncode, 0, check.stderr)
            self.assertEqual(run([FC, *STRICT_FREE, str(output / "check.f")]).returncode, 0)
            self.assertEqual(run([FC, *LEGACY_FREE, str(output / "check.f")]).returncode, 0)

            forward = run([str(FORTAD), "--mode", "forward", "--proc", "top", "--indep", "a,b,c,d", "--name", "top_d", "--module", "top_d_mod", "--output", str(output / "forward.f"), str(source)])
            self.assertEqual(forward.returncode, 0, forward.stderr)
            self.assertEqual(run([FC, *STRICT_FREE, str(output / "forward.f")]).returncode, 0)
            self.assertEqual(run([FC, *LEGACY_FREE, str(output / "forward.f")]).returncode, 0)

            reverse = run([str(FORTAD), "--mode", "reverse", "--proc", "top", "--indep", "a,b,c", "--dep", "d", "--name", "top_b", "--module", "top_b_mod", "--output", str(output / "reverse.f"), str(source)])
            self.assertEqual(reverse.returncode, 0, reverse.stderr)
            self.assertTrue((output / "reverse.f").is_file())
            strict = run([FC, *STRICT_FREE, str(output / "reverse.f")])
            legacy = run([FC, *LEGACY_FREE, str(output / "reverse.f")])
            self.assertNotEqual(strict.returncode, 0, strict.stderr)
            self.assertNotEqual(legacy.returncode, 0, legacy.stderr)
            self.assertIn("d_b", strict.stderr)
            self.assertIn("INTENT(IN)", strict.stderr)


if __name__ == "__main__":
    unittest.main(verbosity=1)
